const ACTION_TYPE = {
    NOTES_DATA_LOADING:"NOTES_DATA_LOADING",
    NOTES_DATA_LOADING_SUCCESS:"NOTES_DATA_LOADING_SUCCESS", // means products get successfully
    NOTES_DATA_LOADING_ERROR:"NOTES_DATA_LOADING_ERROR", // means any error occured in API
    ADD_NOTE:"ADD_NOTE",
    UPDATE_NOTE:"UPDATE_NOTE",
    DELETE_NOTE:"DELETE_NOTE:"
}
export default ACTION_TYPE